FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scripts/ ./scripts/
COPY flyway_migration/ ./flyway_migration/

CMD ["python", "scripts/populate_mysql.py"]
